### ISSUE TITLE
Version reported as 0.0.0

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/control-feedstock#27]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

From conda list:

`    control:                       0.9.3.post2-pyhd8ed1ab_0      conda-forge`

From pip check:

`control                       0.0.0`

Maybe there's a setuptools-scm problem somewhere, or similar?

### Installed packages

```shell
See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=694959&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642
```

### Environment info

```shell
See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=694959&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642
```

**Comment by moorepants** [comment]
Have you checked installing only using pip? Does it also give an incorrect version number?

The conda binary is built from the pypi source release, so my guess is that the issue would be there, not here.

**Comment by bnavigator** [comment]
Thanks for the report @jaimergp. Indeed the setuptools-scm build requirement was missing from the recipe.

**Comment by jaimergp** [comment]
Thank you!
