### ISSUE TITLE
linux python 3.6 build needs to be restarted

### ISSUE THREAD

**Issue by murrayrm** [conda-forge/control-feedstock#9]
The circleci build for linux-64 python-3.6 failed: https://circleci.com/gh/conda-forge/control-feedstock/43?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Looks like the issue was with loading a docker image => should just need to be restarted.  Not sure how to do that (I don't seem to have permissions). 

All other builds successful and there is a linux-64 python-3.6 build available from the previous update => not critical.

**Comment by moorepants** [comment]
@conda-forge/staged-recipes Can someone restart this build?

**Comment by beckermr** [comment]
You are a maintainer on the recipe so you should be able to restart the build with your GitHub credentials by logging into the ci services. 

I’d try it out!

If you are still having trouble, you will want to ping conda-forge/core as the staged recipes team (except for people on it who are also core devs) does not have permissions across all repos.

**Comment by beckermr** [comment]
At least I don’t think the staged recipes team has those permissions...

**Comment by beckermr** [comment]
I certainly cannot restart it.

**Comment by murrayrm** [comment]
I was able to log in and restart.  Sorry for the bother (didn't know I had that superpower).

**Comment by moorepants** [comment]
I logged in and didn't seem to have permissions to restart. Maybe I did it wrong.

Also, I was told to ping staged-recipes in the past for general questions. Must have misinterpreted.

**Comment by beckermr** [comment]
No worries @moorepants! Pinging the staged recipes group is indeed a great idea! It is just that most of us can’t do most things. :(
